### ISSUE TITLE
hostname `extensionscdn.joomla.org` no longer resolves

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/install-from-web-server#61]
I hear you have been messing with CDNs for official sites recently. 

Well, Your CDN for the Install From Web images is now breaking install from web images because the hostname `extensionscdn.joomla.org` no longer resolves

EG:
https://extensionscdn.joomla.org/cache/fab_image/logo/5c7916be34802_400x175.png

<img width="1594" alt="Screenshot 2021-08-15 at 01 49 31" src="https://user-images.githubusercontent.com/400092/129463619-6ed715d9-ce12-43a8-8917-d9f271a0af5b.png">

**Comment by wilsonge** [comment]
Someone needs to update the CDN property in the component here https://github.com/joomla/install-from-web-server/blob/4479cb21830d8a6a1e898e8c4394f4ea2bd29859/administrator/components/com_apps/config.xml#L7-L14 But I don't have access to the site (as far as i know anyhow)

**Comment by Llewellynvdm** [comment]
@conconnl yet another reason not to take down the CDN domain... I think I have access to change this, little occupied now, but will take a look later today. We in the JED have been working on removing this old CDN from all our systems (the last few days), must have missed this one.
